<?php
/**
 * Created by PhpStorm.
 * User: Ignatenkov Nikita
 * Site: http://ignatenkovnikita.ru/
 * Date: 04.07.2016
 * Time: 16:25
 */

namespace sevenfloor\zagruzka;


use yii\base\Component;
use yii\helpers\ArrayHelper;
use yii\httpclient\Client;

class ClientZagruzka extends Component
{

    /** @var  string */
    public $url;

    /** @var  string */
    public $login;

    /** @var  string */
    public $pass;

    /** @var  string */
    public $urlCallback;

    /** @var  \yii\httpclient\Client $_client */
    private $_client;

    public function init()
    {
        $this->_client = new Client(['baseUrl' => $this->url]);
        parent::init(); // TODO: Change the autogenerated stub
    }

    private function send($url, $data)
    {
        $params = ArrayHelper::merge([
            'login' => $this->login,
            'pass' => $this->pass,
        ], $data);
        return $this->_client->get($url, $params)->send();
    }

    public function pay($phone, $sum)
    {
        $data = [
            'phone' => $phone,
            'sum' => $sum
        ];
        $response = $this->send('api', $data);

        if ($response->isOk) {
            return $response;

        }
    }

    public function balance()
    {
        $response = $this->send('balance', []);
        if ($response->isOk) {
            return $response->getData();
        }
    }


}